Repository johnbedeir/Devops-Tools-Documentation, pull requests merged in 2023-04, with the labels that each got.

#246 NOSTORY: Fixing-Issues
  Docker-Compose/simple-docker-compose-project/README.md
  Github-Actions/Docker_Img-GCR/.github/workflows/gcr.yml
  Github-Actions/Docker_Img-GCR/.gitignore
  Github-Actions/Docker_Img-GCR/Dockerfile
  Github-Actions/Docker_Img-GCR/README.md
  Terraform/DigitalOcean/Ubuntu_Droplet/README.md
Labels: documentation, enhancement

#248 NOSTORY: Github-Actions-Wrokflow-Docker-Img-ACR
  Cluster-Backup/Kasten-Minikube/Linux_delete.sh
  DevOps-Pipeline-Monitoring/JenkinsPipeline/Jenkinsfile-Deploy/promethues.sh
  Github-Actions/Docker_Img_ACR/.github/workflows/acr.yml
  Github-Actions/Docker_Img_ACR/Dockerfile
  Github-Actions/Docker_Img_ACR/README.md
  Github-Actions/Docker_Img_ACR/imgs/access-keys.png
  Github-Actions/Docker_Img_ACR/imgs/acr.png
  Github-Actions/Docker_Img_GCR/.github/workflows/gcr.yml
  Github-Actions/Docker_Img_GCR/.gitignore
  Github-Actions/Docker_Img_GCR/Dockerfile
  Github-Actions/Docker_Img_GCR/README.md
Labels: documentation, enhancement

#256 NOSTORY: Fix #251, Fix #255
  DevOps-Pipeline-Go/Deploy-Minikube/Dockerfile
  DevOps-Pipeline-Go/Deploy-Minikube/docker-compose.yml
  DevOps-Pipeline-Go/Deploy-Minikube/main.go
  DevOps-Pipeline-Python/Python/docker-compose.yml
Labels: Improvements

#253 #243 adding Mac-delete.sh file
  Cluster-Backup/Kasten-Minikube/Mac-delete.sh
Labels: documentation

#262 NOSTORY: Fix #260 automate-deploy-go-eks
  DevOps-Pipeline-Go/Deploy-EKS/deploy.sh
Labels: Improvements
