Repository johnbedeir/Devops-Tools-Documentation, pull requests merged in 2023-02, with the labels that each got.

#204 Fix #194 Deploy argocd using helm
  Helm/ArgoCD/README.md
  Helm/ArgoCD/argo.png
  Helm/ArgoCD/helm.png
Labels: Improvements

#208 edit-readme
  README.md
Labels: documentation

#212 Monitoring:Locally:Node_Exporter
  Monitoring/Monitoring_Docker/README.md
  Monitoring/Monitoring_Docker/img.png
  Monitoring/Monitoring_Docker/node-exporter/README.md
  Monitoring/Monitoring_Docker/node-exporter/docker-compose.yml
  Monitoring/Monitoring_Docker/prometheus_config/prometheus.yml
Labels: Improvements

#215 Fix #214
  Monitoring/Monitoring_Docker/README.md
Labels: bug

#216 modified README.md
  Ansible/Ansible-Molecule/README.md
Labels: documentation
